==> Consul Connect proxy starting...
    Configuration mode: Agent API
        Sidecar for ID: dashboard
              Proxy ID: dashboard-sidecar-proxy

==> Log data will now stream in as it occurs:

    2024-05-31T15:33:26.370+0800 [INFO]  proxy: Starting listener: listener=127.0.0.1:5000->service:default/default/counting bind_addr=127.0.0.1:5000
    2024-05-31T15:33:26.372+0800 [INFO]  proxy: Proxy loaded config and ready to serve
    2024-05-31T15:33:26.372+0800 [INFO]  proxy: Parsed TLS identity: uri=spiffe://06f214b1-5b8e-a5fa-797a-1d0cdb8d29b8.consul/ns/default/dc/ua-test/svc/dashboard
    2024-05-31T15:33:26.372+0800 [INFO]  proxy: Starting listener: listener="public listener" bind_addr=0.0.0.0:21001
    2024-05-31T15:33:29.517+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:33:39.518+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:33:49.520+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:33:59.521+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:09.522+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:19.523+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:29.524+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:39.525+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:49.527+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:34:59.529+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:09.529+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:19.531+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:29.532+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:39.533+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:49.534+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:35:59.536+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:09.537+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:19.538+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:29.540+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:39.541+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:49.542+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:36:59.547+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:09.550+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:19.551+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:29.553+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:39.555+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:49.556+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:37:59.557+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:09.558+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:19.559+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:29.560+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:39.562+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:49.563+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:38:59.564+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:09.565+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:19.567+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:29.568+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:39.569+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:49.571+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:39:59.573+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:09.575+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:19.576+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:29.577+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:39.579+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:49.579+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:40:59.582+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:09.582+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:19.583+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:29.585+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:39.586+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:49.587+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:41:59.589+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:09.590+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:19.591+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:29.592+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:39.593+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:49.595+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:42:56.033+0800 [INFO]  proxy: Starting listener: listener=127.0.0.1:5000->service:default/default/counting bind_addr=127.0.0.1:5000
    2024-05-31T15:42:56.033+0800 [ERROR] proxy: listener stopped with error: listener=127.0.0.1:5000->service:default/default/counting error="listen tcp 127.0.0.1:5000: bind: address already in use"
    2024-05-31T15:43:00.244+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:43:10.244+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:43:20.246+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:43:30.247+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:43:40.249+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:43:50.250+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:00.251+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:10.253+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:20.254+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:30.256+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:40.257+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:44:50.259+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:00.260+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:10.262+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:20.262+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:30.264+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:40.266+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:45:50.266+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:00.268+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:10.270+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:20.271+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:30.272+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:40.273+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:46:50.275+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:00.276+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:10.277+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:20.278+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:30.280+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:40.281+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:50.283+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:47:56.583+0800 [INFO]  proxy: Starting listener: listener=127.0.0.1:5000->service:default/default/counting bind_addr=127.0.0.1:5000
    2024-05-31T15:47:56.583+0800 [ERROR] proxy: listener stopped with error: listener=127.0.0.1:5000->service:default/default/counting error="listen tcp 127.0.0.1:5000: bind: address already in use"
    2024-05-31T15:48:00.284+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:48:10.284+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:48:20.286+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:48:30.287+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:48:40.289+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:48:50.290+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:00.292+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:10.294+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:20.295+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:30.297+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:40.298+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:49:50.299+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:00.301+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:10.301+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:20.302+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:30.303+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:40.304+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:50:50.304+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:00.306+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:10.307+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:20.309+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:30.311+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:40.311+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:51:50.313+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:00.315+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:10.317+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:20.318+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:30.319+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:40.320+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:52:50.320+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:00.321+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:10.322+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:20.324+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:30.325+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:40.326+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:53:50.328+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:00.328+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:10.331+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:20.332+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:30.334+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:40.335+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:54:50.337+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:00.338+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:10.340+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:20.342+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:30.344+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:40.344+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:55:50.345+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:00.346+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:10.347+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:20.351+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:30.352+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:40.354+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:56:50.355+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:00.356+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:10.357+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:20.359+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:30.360+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:40.361+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:57:50.362+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:00.364+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:10.365+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:20.367+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:30.368+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:40.370+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:58:50.371+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:00.372+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:10.373+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:20.374+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:30.375+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:40.376+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T15:59:50.377+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:00.379+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:10.379+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:20.381+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:30.381+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:40.383+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:00:50.385+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:00.388+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:10.387+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:20.389+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:30.390+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:40.392+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:01:50.393+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:00.395+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:10.397+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:20.398+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:30.399+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:40.401+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:02:50.403+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:00.404+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:10.405+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:20.406+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:30.408+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:40.410+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:03:50.410+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:00.272+0800 [INFO]  proxy: Starting listener: listener=127.0.0.1:5000->service:default/default/counting bind_addr=127.0.0.1:5000
    2024-05-31T16:04:00.272+0800 [ERROR] proxy: listener stopped with error: listener=127.0.0.1:5000->service:default/default/counting error="listen tcp 127.0.0.1:5000: bind: address already in use"
    2024-05-31T16:04:08.214+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:18.215+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:28.217+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:38.218+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:48.220+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:04:58.221+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:08.223+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:18.225+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:28.227+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:38.228+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:48.230+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:05:58.234+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:08.235+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:18.236+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:28.238+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:38.239+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:48.241+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
    2024-05-31T16:06:58.242+0800 [ERROR] proxy.inbound: failed to dial: error="dial tcp 127.0.0.1:9002: connect: connection refused"
